# CMake generated Testfile for 
# Source directory: E:/Github Project/Virtual-Vehicle-OS
# Build directory: E:/Github Project/Virtual-Vehicle-OS/build-win
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(thread_pool_test "E:/Github Project/Virtual-Vehicle-OS/build-win/Debug/thread_pool_test.exe")
  set_tests_properties(thread_pool_test PROPERTIES  LABELS "core" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;76;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(thread_pool_test "E:/Github Project/Virtual-Vehicle-OS/build-win/Release/thread_pool_test.exe")
  set_tests_properties(thread_pool_test PROPERTIES  LABELS "core" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;76;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(thread_pool_test "E:/Github Project/Virtual-Vehicle-OS/build-win/MinSizeRel/thread_pool_test.exe")
  set_tests_properties(thread_pool_test PROPERTIES  LABELS "core" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;76;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(thread_pool_test "E:/Github Project/Virtual-Vehicle-OS/build-win/RelWithDebInfo/thread_pool_test.exe")
  set_tests_properties(thread_pool_test PROPERTIES  LABELS "core" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;76;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
else()
  add_test(thread_pool_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(retry_policy_test "E:/Github Project/Virtual-Vehicle-OS/build-win/Debug/retry_policy_test.exe")
  set_tests_properties(retry_policy_test PROPERTIES  LABELS "core" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;81;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(retry_policy_test "E:/Github Project/Virtual-Vehicle-OS/build-win/Release/retry_policy_test.exe")
  set_tests_properties(retry_policy_test PROPERTIES  LABELS "core" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;81;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(retry_policy_test "E:/Github Project/Virtual-Vehicle-OS/build-win/MinSizeRel/retry_policy_test.exe")
  set_tests_properties(retry_policy_test PROPERTIES  LABELS "core" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;81;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(retry_policy_test "E:/Github Project/Virtual-Vehicle-OS/build-win/RelWithDebInfo/retry_policy_test.exe")
  set_tests_properties(retry_policy_test PROPERTIES  LABELS "core" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;81;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
else()
  add_test(retry_policy_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(logger_format_test "E:/Github Project/Virtual-Vehicle-OS/build-win/Debug/logger_format_test.exe")
  set_tests_properties(logger_format_test PROPERTIES  LABELS "log" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;86;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(logger_format_test "E:/Github Project/Virtual-Vehicle-OS/build-win/Release/logger_format_test.exe")
  set_tests_properties(logger_format_test PROPERTIES  LABELS "log" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;86;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(logger_format_test "E:/Github Project/Virtual-Vehicle-OS/build-win/MinSizeRel/logger_format_test.exe")
  set_tests_properties(logger_format_test PROPERTIES  LABELS "log" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;86;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(logger_format_test "E:/Github Project/Virtual-Vehicle-OS/build-win/RelWithDebInfo/logger_format_test.exe")
  set_tests_properties(logger_format_test PROPERTIES  LABELS "log" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;86;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
else()
  add_test(logger_format_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(interconnect_codec_test "E:/Github Project/Virtual-Vehicle-OS/build-win/Debug/interconnect_codec_test.exe")
  set_tests_properties(interconnect_codec_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;91;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(interconnect_codec_test "E:/Github Project/Virtual-Vehicle-OS/build-win/Release/interconnect_codec_test.exe")
  set_tests_properties(interconnect_codec_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;91;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(interconnect_codec_test "E:/Github Project/Virtual-Vehicle-OS/build-win/MinSizeRel/interconnect_codec_test.exe")
  set_tests_properties(interconnect_codec_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;91;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(interconnect_codec_test "E:/Github Project/Virtual-Vehicle-OS/build-win/RelWithDebInfo/interconnect_codec_test.exe")
  set_tests_properties(interconnect_codec_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;91;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
else()
  add_test(interconnect_codec_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(interconnect_ttl_test "E:/Github Project/Virtual-Vehicle-OS/build-win/Debug/interconnect_ttl_test.exe")
  set_tests_properties(interconnect_ttl_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;96;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(interconnect_ttl_test "E:/Github Project/Virtual-Vehicle-OS/build-win/Release/interconnect_ttl_test.exe")
  set_tests_properties(interconnect_ttl_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;96;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(interconnect_ttl_test "E:/Github Project/Virtual-Vehicle-OS/build-win/MinSizeRel/interconnect_ttl_test.exe")
  set_tests_properties(interconnect_ttl_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;96;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(interconnect_ttl_test "E:/Github Project/Virtual-Vehicle-OS/build-win/RelWithDebInfo/interconnect_ttl_test.exe")
  set_tests_properties(interconnect_ttl_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;96;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
else()
  add_test(interconnect_ttl_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(interconnect_router_exception_test "E:/Github Project/Virtual-Vehicle-OS/build-win/Debug/interconnect_router_exception_test.exe")
  set_tests_properties(interconnect_router_exception_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;101;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(interconnect_router_exception_test "E:/Github Project/Virtual-Vehicle-OS/build-win/Release/interconnect_router_exception_test.exe")
  set_tests_properties(interconnect_router_exception_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;101;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(interconnect_router_exception_test "E:/Github Project/Virtual-Vehicle-OS/build-win/MinSizeRel/interconnect_router_exception_test.exe")
  set_tests_properties(interconnect_router_exception_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;101;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(interconnect_router_exception_test "E:/Github Project/Virtual-Vehicle-OS/build-win/RelWithDebInfo/interconnect_router_exception_test.exe")
  set_tests_properties(interconnect_router_exception_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;101;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
else()
  add_test(interconnect_router_exception_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(interconnect_backpressure_test "E:/Github Project/Virtual-Vehicle-OS/build-win/Debug/interconnect_backpressure_test.exe")
  set_tests_properties(interconnect_backpressure_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;106;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(interconnect_backpressure_test "E:/Github Project/Virtual-Vehicle-OS/build-win/Release/interconnect_backpressure_test.exe")
  set_tests_properties(interconnect_backpressure_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;106;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(interconnect_backpressure_test "E:/Github Project/Virtual-Vehicle-OS/build-win/MinSizeRel/interconnect_backpressure_test.exe")
  set_tests_properties(interconnect_backpressure_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;106;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(interconnect_backpressure_test "E:/Github Project/Virtual-Vehicle-OS/build-win/RelWithDebInfo/interconnect_backpressure_test.exe")
  set_tests_properties(interconnect_backpressure_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;106;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
else()
  add_test(interconnect_backpressure_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(interconnect_metrics_delta_test "E:/Github Project/Virtual-Vehicle-OS/build-win/Debug/interconnect_metrics_delta_test.exe")
  set_tests_properties(interconnect_metrics_delta_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;111;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(interconnect_metrics_delta_test "E:/Github Project/Virtual-Vehicle-OS/build-win/Release/interconnect_metrics_delta_test.exe")
  set_tests_properties(interconnect_metrics_delta_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;111;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(interconnect_metrics_delta_test "E:/Github Project/Virtual-Vehicle-OS/build-win/MinSizeRel/interconnect_metrics_delta_test.exe")
  set_tests_properties(interconnect_metrics_delta_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;111;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(interconnect_metrics_delta_test "E:/Github Project/Virtual-Vehicle-OS/build-win/RelWithDebInfo/interconnect_metrics_delta_test.exe")
  set_tests_properties(interconnect_metrics_delta_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;111;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
else()
  add_test(interconnect_metrics_delta_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(interconnect_config_provider_test "E:/Github Project/Virtual-Vehicle-OS/build-win/Debug/interconnect_config_provider_test.exe")
  set_tests_properties(interconnect_config_provider_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;116;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(interconnect_config_provider_test "E:/Github Project/Virtual-Vehicle-OS/build-win/Release/interconnect_config_provider_test.exe")
  set_tests_properties(interconnect_config_provider_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;116;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(interconnect_config_provider_test "E:/Github Project/Virtual-Vehicle-OS/build-win/MinSizeRel/interconnect_config_provider_test.exe")
  set_tests_properties(interconnect_config_provider_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;116;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(interconnect_config_provider_test "E:/Github Project/Virtual-Vehicle-OS/build-win/RelWithDebInfo/interconnect_config_provider_test.exe")
  set_tests_properties(interconnect_config_provider_test PROPERTIES  LABELS "interconnect" TIMEOUT "10" _BACKTRACE_TRIPLES "E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;116;add_test;E:/Github Project/Virtual-Vehicle-OS/CMakeLists.txt;0;")
else()
  add_test(interconnect_config_provider_test NOT_AVAILABLE)
endif()
